apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # Example: echo -n "your-username" | base64
  username: bGl0ZW1hYXNfYWRtaW4=  # litemaas_admin
  password: Y2hhbmdlLW1lLXBsZWFzZQ==  # change-me-please