apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-backup
  labels:
    app: backend
    component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
