apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "litemaas.backend.fullname" . }}-backup
  labels:
    {{- include "litemaas.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.backup.persistence.storageClass }}
  storageClassName: {{ .Values.backend.backup.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.backup.persistence.size }}
