{{- if and (include "litemaas.redis.host" .) (not .Values.redis.auth.existingSecret) .Values.redis.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litemaas.redis.fullname" . }}
  labels:
    {{- include "litemaas.componentLabels" (dict "context" . "component" "cache") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.redis.auth.password | quote }}
{{- end }}
